Models/DbKayaContext.cs
using System;
using System.Collections.Generic;
using FluentAssertions.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace KayaHukukAdmin.Models;

public partial class DbKayaContext : DbContext
{
    public DbKayaContext()
    {
    }

    public DbKayaContext(DbContextOptions<DbKayaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Referanslar> Referanslars { get; set; }
     protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
	        => optionsBuilder.UseSqlServer("Data Source=(localdb)\\Buse;Initial Catalog=DbKaya");


	protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Referanslar>(entity =>
        {
            entity.ToTable("Referanslar");

            entity.Property(e => e.FirmaAdi).HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

Models/Dto/ReferanslarDto.cs
using System;
using System.Collections.Generic;

namespace KayaHukukAdmin.Models.Dto;

public partial class ReferanslarDto
{
    public int Id { get; set; }

    public string? FirmaAdi { get; set; }
   
    public IFormFile? FirmaLogo { get; set; }
}

Models/ErrorViewModel.cs
namespace KayaHukukAdmin.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Referanslar.cs
using System;
using System.Collections.Generic;

namespace KayaHukukAdmin.Models;

public partial class Referanslar
{
    public int Id { get; set; }

    public string? FirmaAdi { get; set; }

    public string? FirmaLogo { get; set; }

}

Controllers/DefinitionController.cs
using KayaHukukAdmin.Models;
using KayaHukukAdmin.Models.Dto;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics.Eventing.Reader;

namespace KayaHukukAdmin.Controllers
{
	public class DefinitionController : Controller
	{
		private readonly DbKayaContext _context;
		public DefinitionController(DbKayaContext context)
		{
			_context = context;
		}

		public IActionResult Index()
		{
			return View();
		}
		public IActionResult ReferansList()
		{
			return View();
		}
		public IActionResult ReferanslarGridView()
		{
			var referans = _context.Referanslars.ToList();
			return PartialView("ReferanslarGridView", referans);
		}


		public IActionResult ReferanslarForm(int id)
		{
			Referanslar referanslar = new Referanslar();
			if (id == 0)
			{

				return PartialView("ReferanslarForm", referanslar);
			}
			else
			{
				var tblreferans = _context.Referanslars.FirstOrDefault(referanslar => referanslar.Id == id);
				referanslar.FirmaLogo = tblreferans.FirmaLogo;
				referanslar.FirmaAdi = tblreferans.FirmaAdi;
				referanslar.Id = tblreferans.Id;
				return PartialView("ReferanslarForm", referanslar);
			}


		}
		[HttpPost]
		public IActionResult SaveReferans(ReferanslarDto model)
		{

			byte[] firmaLogoBytes;

			// MemoryStream kullanarak IFormFile'den byte array'e dönüştürme
			using (var memoryStream = new MemoryStream())
			{
				model.FirmaLogo.CopyTo(memoryStream);
				firmaLogoBytes = memoryStream.ToArray();
			}
			if (model.Id == 0)
			{
				Referanslar referanslar = new Referanslar();

				referanslar.FirmaAdi = model.FirmaAdi;
				referanslar.FirmaLogo = Convert.ToBase64String(firmaLogoBytes);   // FirmaLogo'yu byte[] olarak saklıyoruz
				_context.Referanslars.Add(referanslar);

			}
			else
			{
				// Mevcut referansı güncelleme
				var existingReferans = _context.Referanslars.FirstOrDefault(r => r.Id == model.Id);
				if (existingReferans != null)
				{
					existingReferans.FirmaAdi = model.FirmaAdi;
					existingReferans.FirmaLogo = Convert.ToBase64String(firmaLogoBytes);
					_context.Referanslars.Update(existingReferans);
				}
			}

			_context.SaveChanges();
			return RedirectToAction("ReferansList");

		}
		public IActionResult ReferansSil(int? id)
		{

			if (id == null)
			{
				return NotFound();
			}


			var referans = _context.Referanslars.Find(id.Value);
			if (referans == null)
			{

			}
			_context.Referanslars.Remove(referans);
			_context.SaveChanges();
			return RedirectToAction("ReferansList");
		}
		[HttpPost, ActionName("Delete")]
		public IActionResult DeletePOST(int? id)
		{
			var referans = _context.Referanslars.Find(id);
			if (referans == null)
			{
				return NotFound();
			}
			_context.Referanslars.Remove(referans);
			_context.SaveChanges();
			return RedirectToAction("ReferansList");
		}
		

	}
}

Controllers/HomeController.cs
using KayaHukukAdmin.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace KayaHukukAdmin.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Definition/ReferansList.cshtml
<a style="float:right;margin-bottom:10px;" onclick="showInPopup('@Url.Action("ReferanslarForm","Definition",new {id=0},Context.Request.Scheme)','Yeni Ekle')"
   class="btn btn-info text-white">
	<i class="fas fa-pencil-alt"></i>Yeni Ekle
</a>


<div id="divDataTable"></div>

@section Scripts {
	<script>
        $(window).load(function () {
            RefreshGrid();
        });

        function RefreshGrid() {

            var exportStatus = true;
            $.ajax({
                url: "ReferanslarGridView/",
                success: function (result) {
                    $('#divDataTable').html(result);
                    $('#productsTable').DataTable().destroy();
                    $('#productsTable').DataTable({
                        dom: 'Bfrtip',
                        buttons: (exportStatus == true) ? ['pdf', 'excel'] : [],
                        "pageLength": 25,
                        "bLengthChange": false,
                        "ordering": false,
                    
                    }).draw();
                }
            });
        }
	</script>
}

Views/Definition/ReferansSil.cshtml
@model KayaHukukAdmin.Models.Referanslar

<div class="modal-body">
	<form id="ReferansSilForm" method="post" action="/Definition/DeleteReferans">
		<div class="form-group">
			<label for="FirmaLogo">Firma Logo</label>
			<input type="text" class="form-control" id="FirmaLogo" name="FirmaLogo" value="@Model.FirmaLogo" readonly>
		</div>
		<div class="form-group">
			<label for="FirmaAdi">Firma Adı</label>
			<input class="form-control" id="FirmaAdi" name="FirmaAdi" value="@Model.FirmaAdi" readonly>
		</div>
		<input type="hidden" name="Id" value="@Model.Id" />
		<div class="modal-footer justify-content-between">
			<button type="button" class="btn btn-default" data-bs-dismiss="modal">Kapat</button>
			<button type="submit" class="btn btn-danger">Sil</button>
		</div>
	
	</form>
</div>

Views/Definition/ReferanslarForm.cshtml
@model KayaHukukAdmin.Models.Referanslar


<div class="modal-body">
	<!-- Ürün ekleme formu -->
	<form id="ReferansEkleForm" enctype="multipart/form-data" method="post" action="/Definition/SaveReferans">
		<div class="form-group">
			<label for="FirmaLogo">Firma Logo</label>
			<input type="file" class="form-control" id="FirmaLogo" value="@Model.FirmaLogo" name="FirmaLogo" required>
			<img src="@Model.FirmaLogo" alt="Firma Logo" />
		</div>
		<div class="form-group">
			<label for="FirmaAdi">Firma Adı</label>
			<input class="form-control" id="FirmaAdi" name="FirmaAdi" value="@Model.FirmaAdi" required>
		</div>
		<div class="modal-footer justify-content-between">
			<button type="button" class="btn btn-default" data-bs-dismiss="modal">Kapat</button>
			<button type="submit" class="btn btn-primary">Kaydet</button>
		</div>
		<input type="hidden" id="Id" name="Id" value="@Model.Id" />
		
	</form>
</div>

Views/Definition/ReferanslarGridView.cshtml
@model IEnumerable<KayaHukukAdmin.Models.Referanslar>

<table id="productsTable" class="display table table-striped">
	<thead>
		<tr>
			<th class="col-md-1">ID</th>
			<th class="col-md-5">Firma Adı</th>
			<th class="col-md-4">Firma Logo</th>
			<th class="col-md-2">Islem</th>

		</tr>
	</thead>
	<tbody>
		@foreach (var referans in Model)
		{
			<tr>
				<td>@referans.Id</td>
				<td>@referans.FirmaAdi</td>

				<td>
					<img src="data:image/png;base64,@referans.FirmaLogo" alt="Firma Logo" style="max-width: 100px; max-height: 100px;" />
				</td>

				<td>
					<div class="button-container">
						<a class="btn btn-info text-white button delete-button" style="margin-top:10px;margin-left:10px" onclick="Delete($(this));" data-url="ReferansSil" data-id="@referans.Id">Sil</a>
						<a style="float:right;margin-bottom:10px; margin-top:10px" onclick="showInPopup('@Url.Action("ReferanslarForm", "Definition", new { id = referans.Id }, Context.Request.Scheme)','Güncelle')"
					   class="btn btn-info text-white">
						<i class="fas fa-pencil-alt"></i>Güncelle
					</a>
					</div>
				</td>
			</tr>
		}
		<style>
			.button{
				height: 50px; /* Uzunluğu ayarlar */
				display: flex; /* İçerik hizalamasını sağlar */
				align-items: center; /* Dikeyde ortalar */
				justify-content: center; /* Yatayda ortalar */
				text-align: center; /* Yazıyı ortalar *
			  }
		</style>
	</tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Header.cshtml
    
<!-- Raw Links -->
 <div class="col-md-3 col-sm-3 col-xs-3 clearfix">
    <div style=" display: inline;" class="list-inline links-list pull-right">
        <ul class="list-inline links-list pull-right">
            <li style="display:inline">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
            <li style=" display: inline;">
                
            </li>
            <li style=" display: inline;" class="sep"></li>
            <li style=" display: inline;">
                <a style="color: #373e4a;" class="bottomNav" onclick="history.go(-1); return false;" href="#">
                    &nbsp;&nbsp;&nbsp;Geri <i class="entypo-back right"></i>
                </a>
            </li>
            <li style=" display: inline;" class="sep"></li>
            <li style=" display: inline;">
                <a style="color: #373e4a;" href="/LogOut">
                    &nbsp;&nbsp;&nbsp;Çıkış <i class="entypo-logout right"></i>
                </a>
            </li>
        </ul>

    </div>
</div> 

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="Muhtar Web" />
    <meta name="author" content="" />
    <link rel="icon" href="../images/favicon.ico">
    <title>Muhtarlık</title>
    <link href="~/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css" rel="stylesheet" />
    <link href="~/css/font-icons/entypo/css/entypo.css" rel="stylesheet" />
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic">
    <link href="~/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/neon-core.css" rel="stylesheet" />
    <link href="~/css/neon-forms.css" rel="stylesheet" />
    <link href="~/css/neon-theme.css" rel="stylesheet" />

    <link href="~/css/custom.css" rel="stylesheet" />
    <link href="~/css/wopro.css" rel="stylesheet" />
    <link href="~/css/sweetalert.css" rel="stylesheet" />
    <script src="~/scripts/custom.js"></script>
    <script src="~/js/jquery-1.11.3.min.js"></script>
    <script src="~/js/jquery.inputmask.bundle.js"></script>
    <script src="~/js/toastr.js"></script>
    <script src="~/js/toastr.js"></script>
    <script src="~/scripts/custom.js"></script>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

    <link href="~/Content/DataTables/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/buttons.dataTables.min.css" rel="stylesheet" />
    <link href="~/content/datatables/css/toastr.min.css" rel="stylesheet" />

</head>
<body class="page-body  page-fade white" data-url="">
    <div class="page-container">
        <!-- add class "sidebar-collapsed" to close sidebar by default, "chat-visible" to make chat appear always -->
        @Html.Partial("_LeftMenu")

        <div class="main-content">

            <div class="row">
                @Html.Partial("_Header")
            </div>
            <hr />
            @RenderBody()
            <br />
            <!-- Footer -->
            @*<footer class="main">

            &copy 2015 <strong>Neon</strong> Admin Theme by <a href="http://laborator.co" target="_blank">Laborator</a>

            </footer>*@
        </div>
    </div>


    <!-- Imported styles on this page -->

    <link href="~/js/jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" />
    <script src="~/js/gsap/TweenMax.min.js"></script>
    <script src="~/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js"></script>
    <!-- Bottom scripts (common) -->
    <script src="~/js/bootstrap.js"></script>
    <script src="~/js/joinable.js"></script>
    <script src="~/js/resizeable.js"></script>
    <script src="~/js/neon-api.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <!-- Sweet Alert -->
    <script src="~/js/sweetalert.min.js"></script>
    <script src="~/js/sweetalert-dev.js"></script>
    <!-- JavaScripts initializations and stuff -->
    <script src="~/js/neon-custom.js"></script>
    <!-- Demo Settings -->
    <script src="~/js/neon-demo.js"></script>

    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script src="~/js/datatables/Buttons-1.0.3/js/dataTables.buttons.min.js"></script>
    <script src="~/js/datatables/Buttons-1.0.3/js/buttons.flash.min.js"></script>
    <script src="~/js/datatables/JSZip-2.5.0/jszip.min.js"></script>
    <script src="~/js/datatables/pdfmake-0.1.18/build/pdfmake.min.js"></script>
    <script src="~/js/datatables/pdfmake-0.1.18/build/vfs_fonts.js"></script>
    <script src="~/js/datatables/Buttons-1.0.3/js/buttons.html5.min.js"></script>
    <script src="~/js/datatables/Buttons-1.0.3/js/buttons.print.min.js"></script>




    @RenderSection("scripts", false),
    ,

</body>
</html>
<div class="modal" id="form-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div id="divContent" class="modal-body">
            </div>
        </div>
    </div>
</div>

Views/Shared/_LeftMenu.cshtml
 <div class="sidebar-menu fixed">
    <div class="sidebar-menu-inner">
            <div class="logo">
                <a href="index.html" style="color:white;"    class="logo d-flex align-items-center me-auto me-lg-0">
                    <h1 class="sitename">KH</h1>
                    <span class="nokta">.</span>
                </a>
            </div>

        <ul style="margin-top:30px;" id="main-menu" class="main-menu">
            <!-- add class "multiple-expanded" to allow multiple submenus to open -->
            <!-- class "auto-inherit-active-class" will automatically add "active" class for parent elements who are marked already with class "active" -->
            <li>
                <a href="~/Home/DashBoard">
                    <i class="entypo-home"></i>
                    <span class="title">Bilgi Paneli</span>
                </a>
            </li>
            <li>
                <a href="~/Definition/ReferansList">
                    <i class="entypo-archive"></i>
                    <span class="title">Referanslar</span>
                </a>
            </li>
        </ul>
   </ul>
    </div>
</div>  
<style>
    .sitename{
        margin-left:30px;
        margin-top:37px;
    }
    .nokta{
        color:orange;
        font-size: 70px;
        display: inline-block;
    }
</style>